### ISSUE TITLE
爬虫程序运行会卡在 ”获取用户标识步骤“ 。但是exe文件没有这个问题。

### ISSUE THREAD

**Issue by peacemo** [IshtarTang/weibo_spider#1]
如题

----------------------------

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\carlchen\workspace\temp> py .\spider.py
检查配置文件
检查配置项
检查配置项兼容
配置检查完成
获取用户标识

**Comment by peacemo** [comment]
这个py文件名我自己改了，后来改回weibo_spider.py后运行正常，不知道是不是这个问题。

如果确认是这个问题，就可以关闭issue了😂😂😂

**Comment by IshtarTang** [comment]
不是文件名问题，获取用户标识会发一次请求，卡在这里是请求失败，重新启动程序就可以解决。

**Comment by IshtarTang** [comment]
不过其实不该卡住的，我去改一下

**Comment by peacemo** [comment]
> 不是文件名问题，获取用户标识会发一次请求，卡在这里是请求失败，重新启动程序就可以解决。

OK，我试了几遍好像是请求的问题。不过发现程序还有个关于时间戳的小问题，我待会再开个issue。
